# Example microservice definition.
# This definition should consist of a ReplicaSet.

kind: ReplicaSet
apiVersion: extensions/v1beta1
metadata: 
  # Note: Name will have a per-deployment guid appended
  name: server
  annotations:
    # Name of service which exposes this RS
    #   This is used for building the service's selector
    zenoss.org/service: service
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: the-server
        image: gcr.io/${PROJECT_NAME}/service:1.0
        resources:
          requests:
            cpu: 5m
            memory: 50M


